resolver: lts-9.14
extra-deps:
- git: https://github.com/rcook/aws-simple.git
  commit: ac63c070227dbcd28a35942285514d029cff2d6d
- amazonka-1.5.0
- amazonka-core-1.5.0
- amazonka-dynamodb-1.5.0
- amazonka-ec2-1.5.0
- amazonka-iam-1.5.0
- amazonka-lambda-1.5.0
- amazonka-rds-1.5.0
- amazonka-s3-1.5.0
- amazonka-sdb-1.5.0
- amazonka-sqs-1.5.0
- amazonka-ssm-1.5.0
- amazonka-sts-1.5.0
