resolver: lts-9.14
packages:
- .
- ../amazonka/amazonka
- ../amazonka/amazonka-dynamodb
- ../amazonka/amazonka-ec2
- ../amazonka/amazonka-iam
- ../amazonka/amazonka-lambda
- ../amazonka/amazonka-rds
- ../amazonka/amazonka-s3
- ../amazonka/amazonka-sdb
- ../amazonka/amazonka-sqs
- ../amazonka/amazonka-ssm
- ../amazonka/amazonka-sts
- ../amazonka/core
